services:
  logger:
    image: im-logger:latest
    volumes:
      - db-data:/db-data
  api:
    image: im-api:latest
    volumes:
      - db-data:/db-data
    ports:
      - "8080:8080"

volumes:
  db-data:

